import type { ProviderSelectors } from "../../core/providers/contracts";

export const deepseekSelectors = {
  composer: [
    "textarea#chat-input",
    "textarea.ds-scroll-area",
    "textarea[class*='ds-']",
    "textarea[placeholder*='DeepSeek']",
    "textarea[placeholder]",
    "div[contenteditable='true']",
  ],
  submit: [
    "div[role='button'].ds-button.ds-button--primary.ds-button--filled.ds-button--circle:not(.ds-button--disabled):not([aria-disabled='true'])",
    "div[role='button'].ds-button--primary.ds-button--circle:not(.ds-button--disabled):not([aria-disabled='true'])",
    "button[aria-label*='发送']:not(:disabled):not([aria-disabled='true'])",
    "button[aria-label*='Send']:not(:disabled):not([aria-disabled='true'])",
    "button[type='submit']:not(:disabled):not([aria-disabled='true'])",
  ],
  login: [
    "a[href*='login']",
    "button[class*='login' i]",
    "[class*='login' i] button",
    "input[type='tel']",
  ],
  responses: [
    "[data-virtual-list-item-key]:has(.ds-markdown)",
    ".ds-assistant-message:has(.ds-markdown)",
    "[class*='assistant-message']:has(.ds-markdown)",
    ".assistant-response",
    "[data-role='assistant']",
    ".ds-assistant-message-main-content",
    ".ds-markdown:not(.ds-think-content .ds-markdown)",
  ],
  responseContent: [
    ".ds-assistant-message-main-content .ds-markdown",
    ".ds-assistant-message-main-content",
    ".ds-markdown:not(.ds-think-content .ds-markdown)",
  ],
  responseExclude: [
    ".ds-think-content",
    "[class*='think-content']",
    "[class*='reasoning']",
    "[class*='search-plan']",
    "[class*='search-process']",
    "[class*='search-status']",
    "[class*='tool-call']",
    "[role='status']",
  ],
  responseCapture: {
    turnTiers: [
      {
        id: "virtual-turn",
        confidence: "canonical",
        selectors: ["[data-virtual-list-item-key]:has(.ds-markdown)"],
      },
      {
        id: "assistant-turn",
        confidence: "semantic",
        selectors: [
          ".ds-assistant-message:has(.ds-markdown)",
          "[class*='assistant-message']:has(.ds-markdown)",
          ".assistant-response",
          "[data-role='assistant']",
        ],
      },
      {
        id: "content-fallback",
        confidence: "fallback",
        selectors: [
          ".ds-assistant-message-main-content",
          ".ds-markdown:not(.ds-think-content .ds-markdown)",
        ],
      },
    ],
    finalContainers: [".ds-assistant-message-main-content"],
    contentBlocks: [".ds-markdown:not(.ds-think-content .ds-markdown)"],
    exclude: [
      ".ds-think-content",
      "[class*='think-content']",
      "[class*='reasoning']",
      "[class*='search-plan']",
      "[class*='search-process']",
      "[class*='search-status']",
      "[class*='tool-call']",
    ],
    statusOnly: ["[role='status']"],
    interrupted: ["[role='status']"],
    interruptedLabels: ["已停止", "Stopped"],
    observeAttributes: ["aria-busy", "data-state", "data-virtual-list-item-key", "data-id"],
    allowStableCompletionWithoutGenerating: true,
  },
  generating: [
    "button[aria-label*='停止']",
    "button[aria-label*='Stop']",
    "[data-testid='stop-button']",
    "[aria-busy='true']",
  ],
  responseTimeoutMs: 600_000,
  responseQuietMs: 12_000,
  responsePollMs: 1_000,
  newConversation: ["button[aria-label*='新对话']", "[role='button'][aria-label*='新对话']"],
  newConversationLabels: ["开启新对话", "新对话", "New chat"],
} as const satisfies ProviderSelectors;
