import type { ProviderSelectors } from "../../core/providers/contracts";

export const qwenSelectors = {
  composer: [
    "[data-chat-input-shell='true'] textarea",
    "textarea.message-input-textarea",
    "textarea#chat-input",
    "[data-slate-editor='true'][contenteditable='true']",
    "[role='textbox'][contenteditable='true']",
    "textarea[placeholder*='千问']",
    "textarea[placeholder*='问']",
    "textarea[placeholder*='Qwen']",
    "textarea[placeholder*='Ask']",
    "textarea[placeholder]",
    "div[contenteditable='true'].ProseMirror",
    "div[contenteditable='true']",
  ],
  submit: [
    "[data-chat-input-shell='true'] button[class*='send' i]",
    "button.send-button",
    "button[class*='send' i]",
    "button[aria-label*='发送']",
    "button[aria-label*='send' i]",
    "button[aria-label*='submit' i]",
    "button[title*='send' i]",
    "button[title*='submit' i]",
    "button[type='submit']",
    "[role='button'][aria-label*='send' i]",
    "[class*='send' i][role='button']",
  ],
  login: ["a[href*='login']", "button[class*='login']"],
  blocked: [
    "iframe[src*='captcha' i]:not([hidden]):not([aria-hidden='true'])",
    "iframe[src*='verify' i]:not([hidden]):not([aria-hidden='true'])",
    "#baxia-dialog-content:has(iframe[src*='captcha' i], iframe[src*='verify' i], [role='slider'], .nc_scale)",
    ".baxia-dialog:has(iframe[src*='captcha' i], iframe[src*='verify' i], [role='slider'], .nc_scale)",
    ".nc-container:has(.nc_wrapper, .nc_scale, [role='slider'], [class*='slider' i])",
    "[id^='nc_'][id$='_wrapper']:has([role='slider'], .nc_scale, [class*='slider' i])",
    "[class*='captcha-container' i]:has(iframe, input, button, [role='slider'])",
    "[class*='slider-verify' i]:has(input, button, [role='slider'], [class*='slider' i])",
  ],
  responses: [
    ".chat-round[data-chat] [data-chat-answers-wrap]",
    "[data-chat-answers-wrap].chat-answers-card-wrap",
    ".assistant-response",
    "div.response-message-content.phase-answer",
    "div.response-message-content",
    "div.chat-response-message",
    "div[id^='chat-response-message-']",
    "[data-role='assistant']",
    "[class*='answer-content']",
  ],
  responseContent: [
    ".answer-text.md-text-card .qk-markdown",
    ".answer-text.md-text-card",
    ".qk-markdown",
    ".response-message-content.phase-answer",
    ".response-message-content",
    ".markdown-body",
    "[class*='answer-content']",
  ],
  responseExclude: [
    ".answer-meta",
    "[data-answer-feedback-toolbar]",
    ".answer-receiving-card",
    ".chat-message-mask",
  ],
  generating: [
    ".last-message-item .answer-receiving-card",
    ".answer-receiving-card",
    "[data-chat-input-shell='true'] button.stop-button",
    "button.stop-button",
    "button[aria-label*='停止']",
    "button[aria-label*='stop' i]",
    "[class*='stop' i][role='button']",
  ],
  responseTimeoutMs: 600_000,
  responseQuietMs: 6_000,
  responsePollMs: 1_000,
  newConversation: ["button[aria-label*='新建对话']", "[role='button'][aria-label*='新建对话']"],
  newConversationLabels: ["新建对话", "新对话", "New chat"],
} as const satisfies ProviderSelectors;
